import "./globals.css";
import React, { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import MousePosition from "@/components/MousePosition";
import Scrolling from "@/components/Scrolling";
import DecortiveTrees from "@/components/DecorativeTrees";
import MainScene from "@/scenes/Virtudes";
import { ThemeProvider } from "@/context/ThemeContext";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("LAOYUT RENDER");
  return (
    <html lang="en">
      <head>
        <title>Parque das Virtudes</title>
        <meta
          name="description"
          content="Web-site of Parque das Virtudes in Porto, Portugal"
        />
        <link
          href="https://api.fontshare.com/v2/css?f[]=melodrama@1&display=swap"
          rel="stylesheet"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@200;300;400&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <ThemeProvider>
          <Header />

          <main id="main" className="h-screen overflow-hidden p-0">
            {/* <Filter /> */}
            <Scrolling targetId="main">
              <div id="canvas-wrapper" className="fixed h-full w-full z-0">
                <Suspense>
                  <MousePosition>
                    <MainScene />
                  </MousePosition>
                </Suspense>
              </div>

              <div className="fixed h-full w-full z-0">
                <DecortiveTrees />
              </div>

              {children}
            </Scrolling>
          </main>

          <footer className="fixed bottom-0 right-0 w-full z-10 mix-blend-difference">
            <Footer />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
